# help I don't know what I'm doing

name: mc-publish

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: Kir-Antipov/mc-publish@v3.1
        with:
          modrinth-id: YvHGNxlf
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # curseforge-id: XXXXX
          # curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
